version: "3"

services:
    nginx:
        image: nginx:1.11
        depends_on:
            - php-fpm
        links:
            - php-fpm
        environment:
            - NGINX_PORT=80
            - FASTCGI_HOST=php-fpm
            - FASTCGI_PORT=9000
            - DOCUMENT_ROOT=/usr/local/src/shortener/web
        ports:
            - '8095:80'
        volumes:
            - .:/usr/local/src/shortener
            - ./docker/nginx/templates/default.conf.template:/etc/nginx/conf.d/default.conf.template
            - ./docker/nginx/entrypoint.sh:/entrypoint.sh
        command: "/bin/bash /entrypoint.sh"

    php-fpm:
        build: docker/php
        hostname: php-fpm
        depends_on:
            - db
        extra_hosts:
            - "shortener:127.0.0.1"
        working_dir: /usr/local/src/shortener
        volumes:
            - .:/usr/local/src/shortener
        ports:
            - '9001:9001'

    db:
        build: docker/mysql
        hostname: mysql-docker
        ports:
            - '8989:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 111
        volumes:
            - data:/var/lib/db
        command:
            --max-connections=1000
            --log_output=table
            --general_log=ON
volumes:
    data: {}